//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude ;

pub mod albums ;
pub mod article_tags ;
pub mod articles ;
pub mod categories ;
pub mod photos ;
pub mod posts ;
pub mod tags ;
pub mod users ;