//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super :: albums :: Entity as Albums ;
pub use super :: article_tags :: Entity as ArticleTags ;
pub use super :: articles :: Entity as Articles ;
pub use super :: categories :: Entity as Categories ;
pub use super :: photos :: Entity as Photos ;
pub use super :: posts :: Entity as Posts ;
pub use super :: tags :: Entity as Tags ;
pub use super :: users :: Entity as Users ;